const fs = require('fs');
const content = [
"import { useState, useEffect } from 'react'",
"import { useCart } from '../context/CartContext'",
"import { products } from '../data/products'",
"",
"const links = [",
"  { label: 'Accueil', href: '#accueil' },",
"  { label: 'Boutique', href: '#boutique' },",
"  { label: 'Offres', href: '#offres' },",
"  { label: 'Contact', href: '#contact' },",
"]",
"",
"export default function Navbar({ onOpenCart, onSearch }) {",
"  const { count, total } = useCart()",
"  const fmt = n => n.toLocaleString('fr-FR') + ' F'",
"  const [menuOpen, setMenuOpen] = useState(false)",
"  const [scrolled, setScrolled] = useState(false)",
"  const [isMobile, setIsMobile] = useState(window.innerWidth < 768)",
"  const [query, setQuery] = useState('')",
"  const [results, setResults] = useState([])",
"  const [showResults, setShowResults] = useState(false)",
"",
"  useEffect(() => {",
"    const onScroll = () => setScrolled(window.scrollY > 20)",
"    const onResize = () => setIsMobile(window.innerWidth < 768)",
"    window.addEventListener('scroll', onScroll)",
"    window.addEventListener('resize', onResize)",
"    return () => {",
"      window.removeEventListener('scroll', onScroll)",
"      window.removeEventListener('resize', onResize)",
"    }",
"  }, [])",
"",
"  const handleSearch = (val) => {",
"    setQuery(val)",
"    if (val.length > 1) {",
"      const res = products.filter(p =>",
"        p.name.toLowerCase().includes(val.toLowerCase()) ||",
"        p.cat.toLowerCase().includes(val.toLowerCase())",
"      ).slice(0, 6)",
"      setResults(res)",
"      setShowResults(true)",
"    } else {",
"      setResults([])",
"      setShowResults(false)",
"    }",
"    onSearch?.(val)",
"  }",
"",
"  const handleClickResult = (p) => {",
"    setQuery(p.name)",
"    setShowResults(false)",
"    onSearch?.(p.name)",
"    setTimeout(() => {",
"      document.getElementById('boutique')?.scrollIntoView({ behavior: 'smooth' })",
"    }, 100)",
"  }",
"",
"  const handleNav = (href) => {",
"    setMenuOpen(false)",
"    const el = document.querySelector(href)",
"    if (el) el.scrollIntoView({ behavior: 'smooth' })",
"  }",
"",
"  const clearSearch = () => {",
"    setQuery('')",
"    setResults([])",
"    setShowResults(false)",
"    onSearch?.('')",
"  }",
"",
"  return (",
"    <>",
"      <nav style={{",
"        background: '#fff',",
"        borderBottom: scrolled ? '1px solid #f0e8e0' : '1px solid transparent',",
"        padding: '0 clamp(1rem, 4vw, 3rem)',",
"        height: '64px',",
"        display: 'flex',",
"        alignItems: 'center',",
"        justifyContent: 'space-between',",
"        position: 'sticky',",
"        top: 0,",
"        zIndex: 200,",
"        boxShadow: scrolled ? '0 2px 20px rgba(249,115,22,0.07)' : 'none',",
"        transition: 'all 0.3s',",
"        gap: '1rem',",
"      }}>",
"        <div",
"          onClick={() => handleNav('#accueil')}",
"          style={{ fontFamily: 'Syne, sans-serif', fontWeight: 800, fontSize: '1.5rem', color: '#F97316', letterSpacing: '-0.5px', cursor: 'pointer', flexShrink: 0 }}",
"        >",
"          OCAS",
"        </div>",
"",
"        {!isMobile && (",
"          <ul style={{ display: 'flex', gap: '2rem', listStyle: 'none' }}>",
"            {links.map((l, i) => (",
"              <li key={l.label}>",
"                <a",
"                  href={l.href}",
"                  onClick={e => { e.preventDefault(); handleNav(l.href) }}",
"                  style={{ textDecoration: 'none', color: i === 0 ? '#F97316' : '#555', fontSize: '0.88rem', fontWeight: 600, transition: 'color 0.2s' }}",
"                  onMouseEnter={e => { e.currentTarget.style.color = '#F97316' }}",
"                  onMouseLeave={e => { e.currentTarget.style.color = i === 0 ? '#F97316' : '#555' }}",
"                >",
"                  {l.label}",
"                </a>",
"              </li>",
"            ))}",
"          </ul>",
"        )}",
"",
"        <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>",
"          {!isMobile && (",
"            <div style={{ position: 'relative' }}>",
"              <div style={{ display: 'flex', alignItems: 'center', background: '#f8f3ef', borderRadius: '20px', padding: '7px 14px', gap: '8px', border: showResults ? '1.5px solid #F97316' : '1.5px solid transparent', transition: 'border 0.2s' }}>",
"                <i className='fa-solid fa-magnifying-glass' style={{ color: '#bbb', fontSize: '12px' }}></i>",
"                <input",
"                  value={query}",
"                  onChange={e => handleSearch(e.target.value)}",
"                  onFocus={() => query.length > 1 && setShowResults(true)}",
"                  onBlur={() => setTimeout(() => setShowResults(false), 200)}",
"                  placeholder='Rechercher un produit...'",
"                  style={{ border: 'none', background: 'transparent', fontSize: '0.83rem', outline: 'none', width: '160px', fontFamily: 'Plus Jakarta Sans, sans-serif' }}",
"                />",
"                {query && (",
"                  <button onClick={clearSearch} style={{ background: 'none', border: 'none', cursor: 'pointer', color: '#bbb', fontSize: '11px', padding: 0 }}>",
"                    <i className='fa-solid fa-xmark'></i>",
"                  </button>",
"                )}",
"              </div>",
"              {showResults && results.length > 0 && (",
"                <div style={{ position: 'absolute', top: 'calc(100% + 8px)', left: 0, background: '#fff', borderRadius: '14px', boxShadow: '0 8px 32px rgba(0,0,0,0.12)', border: '1px solid #f0e8e0', overflow: 'hidden', zIndex: 300, minWidth: '300px' }}>",
"                  {results.map(p => (",
"                    <div",
"                      key={p.id}",
"                      onMouseDown={() => handleClickResult(p)}",
"                      style={{ display: 'flex', alignItems: 'center', gap: '12px', padding: '10px 14px', cursor: 'pointer', borderBottom: '1px solid #faf5f0', background: '#fff', transition: 'background 0.15s' }}",
"                      onMouseEnter={e => { e.currentTarget.style.background = '#fff7ed' }}",
"                      onMouseLeave={e => { e.currentTarget.style.background = '#fff' }}",
"                    >",
"                      <div style={{ width: '38px', height: '38px', borderRadius: '10px', background: p.bg, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>",
"                        <i className={p.icon} style={{ fontSize: '1.2rem', color: p.color }}></i>",
"                      </div>",
"                      <div style={{ flex: 1 }}>",
"                        <div style={{ fontSize: '0.83rem', fontWeight: 600, color: '#111' }}>{p.name}</div>",
"                        <div style={{ fontSize: '0.72rem', color: '#aaa', textTransform: 'capitalize' }}>{p.cat}</div>",
"                      </div>",
"                      <div style={{ fontFamily: 'Syne, sans-serif', fontWeight: 800, fontSize: '0.85rem', color: '#F97316', flexShrink: 0 }}>",
"                        {fmt(p.price)}",
"                      </div>",
"                    </div>",
"                  ))}",
"                  <div style={{ padding: '8px 14px', background: '#faf7f5', fontSize: '0.75rem', color: '#aaa', textAlign: 'center' }}>",
"                    {results.length} resultat{results.length > 1 ? 's' : ''} — cliquez pour filtrer",
"                  </div>",
"                </div>",
"              )}",
"              {showResults && results.length === 0 && query.length > 1 && (",
"                <div style={{ position: 'absolute', top: 'calc(100% + 8px)', left: 0, background: '#fff', borderRadius: '14px', boxShadow: '0 8px 32px rgba(0,0,0,0.12)', border: '1px solid #f0e8e0', padding: '1.2rem', textAlign: 'center', zIndex: 300, minWidth: '260px' }}>",
"                  <i className='fa-solid fa-face-frown-open' style={{ color: '#F97316', fontSize: '1.5rem', display: 'block', marginBottom: '6px' }}></i>",
"                  <div style={{ fontSize: '0.83rem', color: '#888' }}>",
"                    Aucun resultat pour <strong style={{ color: '#111' }}>{query}</strong>",
"                  </div>",
"                </div>",
"              )}",
"            </div>",
"          )}",
"",
"          <button",
"            onClick={onOpenCart}",
"            style={{ background: '#F97316', color: '#fff', border: 'none', borderRadius: '22px', padding: '9px 18px', fontWeight: 600, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '8px', fontSize: '0.84rem', fontFamily: 'Plus Jakarta Sans, sans-serif', boxShadow: '0 3px 12px rgba(249,115,22,0.35)', transition: 'all 0.2s', flexShrink: 0 }}",
"          >",
"            <i className='fa-solid fa-bag-shopping'></i>",
"            {count > 0 && (",
"              <span style={{ background: '#fff', color: '#F97316', borderRadius: '50%', width: '18px', height: '18px', fontSize: '10px', fontWeight: 700, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>",
"                {count}",
"              </span>",
"            )}",
"            <span style={{ fontSize: '0.78rem' }}>",
"              {count > 0 ? fmt(total) : 'Panier'}",
"            </span>",
"          </button>",
"",
"          {isMobile && (",
"            <button",
"              onClick={() => setMenuOpen(o => !o)}",
"              style={{ background: 'none', border: '1.5px solid #f0e8e0', borderRadius: '10px', width: '40px', height: '40px', display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer', color: '#555', fontSize: '15px' }}",
"            >",
"              <i className={menuOpen ? 'fa-solid fa-xmark' : 'fa-solid fa-bars'}></i>",
"            </button>",
"          )}",
"        </div>",
"      </nav>",
"",
"      {isMobile && menuOpen && (",
"        <div style={{ position: 'fixed', top: '64px', left: 0, right: 0, background: '#fff', zIndex: 190, borderBottom: '1px solid #f0e8e0', boxShadow: '0 8px 24px rgba(0,0,0,0.08)' }}>",
"          {links.map(l => (",
"            <a",
"              key={l.label}",
"              href={l.href}",
"              onClick={e => { e.preventDefault(); handleNav(l.href) }}",
"              style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '1rem clamp(1rem,4vw,3rem)', color: '#444', textDecoration: 'none', fontWeight: 600, fontSize: '0.95rem', borderBottom: '1px solid #f9f5f0' }}",
"            >",
"              {l.label}",
"              <i className='fa-solid fa-chevron-right' style={{ fontSize: '11px', color: '#F97316' }}></i>",
"            </a>",
"          ))}",
"          <div style={{ padding: '1rem clamp(1rem,4vw,3rem)' }}>",
"            <div style={{ display: 'flex', alignItems: 'center', background: '#f8f3ef', borderRadius: '14px', padding: '9px 14px', gap: '8px' }}>",
"              <i className='fa-solid fa-magnifying-glass' style={{ color: '#bbb', fontSize: '13px' }}></i>",
"              <input",
"                value={query}",
"                onChange={e => handleSearch(e.target.value)}",
"                placeholder='Rechercher un produit...'",
"                style={{ border: 'none', background: 'transparent', fontSize: '0.88rem', outline: 'none', flex: 1, fontFamily: 'Plus Jakarta Sans, sans-serif' }}",
"              />",
"            </div>",
"            {results.length > 0 && (",
"              <div style={{ marginTop: '8px', background: '#fff', borderRadius: '12px', border: '1px solid #f0e8e0', overflow: 'hidden' }}>",
"                {results.map(p => (",
"                  <div",
"                    key={p.id}",
"                    onClick={() => { handleClickResult(p); setMenuOpen(false) }}",
"                    style={{ display: 'flex', alignItems: 'center', gap: '10px', padding: '10px 12px', borderBottom: '1px solid #faf5f0', cursor: 'pointer' }}",
"                  >",
"                    <div style={{ width: '36px', height: '36px', borderRadius: '9px', background: p.bg, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>",
"                      <i className={p.icon} style={{ fontSize: '1.1rem', color: p.color }}></i>",
"                    </div>",
"                    <div style={{ flex: 1 }}>",
"                      <div style={{ fontSize: '0.82rem', fontWeight: 600, color: '#111' }}>{p.name}</div>",
"                      <div style={{ fontSize: '0.7rem', color: '#F97316', fontWeight: 700, fontFamily: 'Syne, sans-serif' }}>{fmt(p.price)}</div>",
"                    </div>",
"                  </div>",
"                ))}",
"              </div>",
"            )}",
"          </div>",
"        </div>",
"      )}",
"    </>",
"  )",
"}"
].join('\n');
fs.writeFileSync('src/components/Navbar.jsx', content);
console.log('OK');
